from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Admin_Management)
admin.site.register(User_Management)
admin.site.register(Vehicle_Management)
admin.site.register(List_your_vehicles_Management)
admin.site.register(Vehicle_Monitoring)
admin.site.register(Co_partnner_Management)
admin.site.register(Country_Management)
admin.site.register(state_Management)
admin.site.register(City_Management)
admin.site.register(Advertisement_Management)
admin.site.register(Listing_Management)
admin.site.register(Templates_Management)
admin.site.register(Fare_Management)
admin.site.register(Notification_To_User)
admin.site.register(Notification_To_CoPartner)
admin.site.register(Fuel_Management)
admin.site.register(Maintainance_Management)
admin.site.register(Refral_Management)
admin.site.register(Refund_Management)
admin.site.register(Transaction_Management)
admin.site.register(Feedback)
admin.site.register(Content_Management)
admin.site.register(SOS)
admin.site.register(Support)
admin.site.register(Terms_Condition)
admin.site.register(Privacy_Policy)

