# Generated by Django 3.2.9 on 2021-12-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corporate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drop_Points',
            new_name='dropup_Points_Management',
        ),
    ]
