# Generated by Django 3.2.9 on 2021-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare_Management_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=80, null=True)),
                ('state', models.CharField(max_length=80, null=True)),
                ('city', models.CharField(max_length=80, null=True)),
                ('fuel_status', models.CharField(max_length=80, null=True)),
                ('trip_type', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Management_outstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=80, null=True)),
                ('state', models.CharField(max_length=80, null=True)),
                ('city', models.CharField(max_length=80, null=True)),
                ('fuel_status', models.CharField(max_length=80, null=True)),
                ('trip_type', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Manangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=80, null=True)),
                ('country', models.CharField(max_length=80, null=True)),
                ('state', models.CharField(max_length=80, null=True)),
                ('city', models.CharField(max_length=80, null=True)),
                ('fuel_status', models.CharField(max_length=80, null=True)),
                ('booking_cat', models.IntegerField(null=True)),
                ('v_id', models.CharField(max_length=80, null=True)),
                ('setment', models.CharField(max_length=80, null=True)),
                ('model', models.CharField(max_length=80, null=True)),
                ('base_fare', models.IntegerField(null=True)),
                ('booking_fee', models.IntegerField(null=True)),
                ('commision_fee', models.IntegerField(null=True)),
                ('per_min_charge', models.IntegerField(null=True)),
                ('per_km_charge', models.IntegerField(null=True)),
                ('minimum_bill', models.IntegerField(null=True)),
                ('tool_tax', models.IntegerField(null=True)),
                ('parking', models.IntegerField(null=True)),
                ('seat', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('edit_button', models.CharField(max_length=80, null=True)),
                ('listing', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
